FROM ubuntu:latest

RUN apt-get update && apt-get install -y apache2 php libapache2-mod-php

RUN a2enmod rewrite


COPY ./var/www/html /var/www/html
RUN chown -R www-data:www-data /var/www/html

# Exponer el puerto 80
EXPOSE 80

# Iniciar Apache
CMD ["apachectl", "-D", "FOREGROUND"]
